In [2]:
matrix1 = np.array([[19, 3, 3], [8, 8, 1]])


matrix2 = np.array([[2, 0, 2], [4, 0, 7]])


print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)


matrix3 = matrix1 + matrix2

print("\nMatrix 3 (Matrix1 + Matrix2):")
print(matrix3)

matrix4 = matrix1 * 2

print("\nMatrix 4 (Matrix1 * 2):")
print(matrix4)


matrix5 = matrix2.T

print("\nMatrix 5 (Transpose of Matrix2):")
print(matrix5)


matrix6 = np.dot(matrix3, matrix5)

print("\nMatrix 6 (Matrix3 multiplied by Matrix5):")
print(matrix6)


sum_matrix3 = np.sum(matrix3)

print("\nSum of all elements in Matrix3:", sum_matrix3)


matrix7 = np.zeros((2, 3), dtype=int)

print("\nMatrix 7 (2x3 Zero Matrix):")
print(matrix7) 


Matrix 1:
[[19  3  3]
 [ 8  8  1]]

Matrix 2:
[[2 0 2]
 [4 0 7]]

Matrix 3 (Matrix1 + Matrix2):
[[21  3  5]
 [12  8  8]]

Matrix 4 (Matrix1 * 2):
[[38  6  6]
 [16 16  2]]

Matrix 5 (Transpose of Matrix2):
[[2 4]
 [0 0]
 [2 7]]

Matrix 6 (Matrix3 multiplied by Matrix5):
[[ 52 119]
 [ 40 104]]

Sum of all elements in Matrix3: 57

Matrix 7 (2x3 Zero Matrix):
[[0 0 0]
 [0 0 0]]
